name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}, PostgreSQL ${{ matrix.postgres }}

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - "3.0"
        rails:
          - "7.0"
        postgres:
          - 10
          - 11
          - 12
          - 13
          - 14
        include: # for backward-compatibility
          - ruby: "2.7"
            rails: "5.2"
            postgres: 10
          - ruby: "3.0"
            rails: "6.1"
            postgres: 10

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_VERSION: ${{ matrix.rails }}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true 'bundle install' and cache

      - name: Check code style
        run: bundle exec rubocop
        continue-on-error: false

      - name: Run tests
        run: bundle exec rake --trace
        continue-on-error: false
